### ISSUE TITLE
How do we submit a company name with two words? Like TJ Max? Missing from the readme and command line doesn't allow for "" or ''. 

### ISSUE THREAD

**Issue by Dataphix** [m8r0wn/crosslinked#1]

**Comment by m8r0wn** [comment]
Hi @Dataphix 

Two word company names can be searched through wrapping the name in quotes, ex:
```python3 crosslinked.py -f 'domain\{first}.{last}' 'tj maxx'```

If you are still having issues, you can encode the company name for direct implementation into the search URL. However, this method would not be compatible with the ```--safe``` option:
```python3 crosslinked.py -f 'domain\{first}.{last}' 'tj%20maxx'```

Company names with apostrophes can be handled the same way: 
```python3 crosslinked.py -f 'domain\{first}.{last}' "o'reilly"```
```python3 crosslinked.py -f 'domain\{first}.{last}' "o%27reilly"```

Good catch, this information is missing from the readme and is probably helpful to other users as well!

**Comment by Dataphix** [comment]
Awesome and thank you!

**Comment by m8r0wn** [comment]
No problem!
-m8r0wn
