### ISSUE TITLE
Remove accents/diacritics

### ISSUE THREAD

**Issue by nuno-carvalho** [m8r0wn/CrossLinked#3]
Very nice app.... works like a charm.

For some languages (like Portuguese), it should remove accents/diacritics, cause it's not used in e-mail addresses.

I get it done with function...
```
def strip_accents(text):
    try:
        text = unicode(text, 'utf-8')
    except NameError: # unicode is a default on python 3 
        pass

    text = unicodedata.normalize('NFD', text)\
           .encode('ascii', 'ignore')\
           .decode("utf-8")

    return str(text)
```
....called before save to file!

**Comment by m8r0wn** [comment]
Hey @nuno-carvalho,

Thanks for the feedback :)

I have actually run into this issue recently myself too, this is great! Ill do some q/a on the code and hope to make a new commit soon! Will leave the issue open until then.

\- m8r0wn

**Comment by m8r0wn** [comment]
Just made a commit that should correct this issue with the ```unidecode``` library. 

Thanks,
\-m8r0wn
