### ISSUE TITLE
bad results

### ISSUE THREAD

**Issue by shanow7** [m8r0wn/CrossLinked#4]
the first member of the e-mail is always the same, regardless of the searched domain???

kamila.kamyk@domain.com
konrad.testowy@domain.com
c2f.americas@domain.com
per.markus@domain.com

kamila.kamyk@vistula.pl
konrad.testowy@vistula.pl
c2f.americas@vistula.pl
per.markus@vistula.pl

**Comment by m8r0wn** [comment]
Hi @shanow7,

Have you tried manually executing the Google and Bing search operators to see if it is truly a false positive? If so, it may have to do with how the company name is defined. One thing I have found is to type exactly how it is formatted on linkedin:

```bash
python3 crosslinked -f '{first}.{last}@company.com' 'Company xzy'
```

**Comment by m8r0wn** [comment]
Closing, need more information
